# repo branches

branches:
  only:
  - master

# job environment

sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# job phases

install:
  - pip install --editable .[test] .

script:
  - pylint subscribers
  - cd ./tests
  - py.test -vv --cov=subscribers --cov-report=term-missing --cov-config=.coveragerc
